### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by treeder** [gochain-io/gochain#249]
Let's get tracing all throughout the system (per Ben's suggestion), starting at the proxy nodes to see where we can optimize. 

https://opencensus.io/

**Comment by jmank88** [comment]
Maybe we can start by replacing this custom timing package https://github.com/gochain-io/gochain/blob/master/common/perfutils/timer.go which already required lots of context wiring.

**Comment by jmank88** [comment]
Trace was enabled and wired through most of the interesting areas with #250. Closing.
