### ISSUE TITLE
Issue when installing the dependencies of gochain

### ISSUE THREAD

**Issue by landedexperts** [gochain-io/gochain#317]
Running `go get ./...` raises this error:
cmd/gochain/main.go:29:2: no Go files in [...]/go/src/go.opencensus.io/exporter/stackdriver

**Comment by jmank88** [comment]
This repo is currently set up to manage dependencies with [`dep`](https://github.com/golang/dep). Does `dep ensure --vendor-only` run successfully?

**Comment by landedexperts** [comment]
CCing Julien Ferte to provide confirmation whether it runs successfully or not.

 

Regards

Kazem

**Comment by landedexperts** [comment]
Thank you, now gochain is working :)

Being quite new to Go, I did not know about `go-dep` beforehand, nor did I install it, so I had gone with `go get./...` instead. Executing directly the line `dep ensure --vendor-only` in the terminal showed the solution thanks to Ubuntu suggestions.
I previously ran into the Prometheus flock lib missing, maybe due to not using `go-dep` as well.

I write down my successful path, on Ubuntu 18.04.1, it might help someone else:
- install `go`,
- install `dep` through the `go-dep` package,
- install gochain by executing `go get github.com/gochain-io/gochain` (having `go` being aware of `gochain` as one of its packages might come in handy in the future),
- run `make dep` then `make` or `make all` (as suggested in the README.md),
- the `make` process prints the path to the `gochain` binary.

Thanks again :)
