### ISSUE TITLE
GoChain on testnet, in light mode

### ISSUE THREAD

**Issue by landedexperts** [gochain-io/gochain#323]
I know that the light mode is experimental already in Geth, but, in practice, it works, for example on Rinkeby.

GoChain on testnet and in light mode does not synchronize.

The line executed is
`./gochain --testnet --cache 1024 --light console`
and it is left running for two days.
Synchronization is expected but does not happen.

The subfolders `body`, `header` and `receipt` under `lightchaindata` only contain the folder `0000000000000000`

On the same machine, GoChain in fast mode on the testnet synchronizes.

**Comment by landedexperts** [comment]
I have launched the GoChain client in light mode on testnet for more than 5 mins, but no syncing.
The list admin.peers is empty.

How much time roughly does it take to sync?
Should I have updated my local copy of the GoChain repository?

**Comment by jmank88** [comment]
Syncing should begin right away, but perhaps it's struggling to find peers running `LES`. You can try adding these peers directly:
```
enode://9db67f8624bf651fa8d560e0abdd9635e9b27b2eb64844d607ba0265c0157738734c7fa90ee42200468e82f063ca42e1e5c61a00d288503e038cef33ecfa2924@35.236.66.130:30303
enode://a5893e5634503a1223c15842a29788f1ef87e3a19f75664819b670afa8a326742e9b1a2c7507c45c2e74a85516fb210d30f76da8bdbda13db1f07aefb26825d1@35.228.164.134:30303
enode://f9fec83c31e3e6ce92f99f92e38f7a7915d94ebc16edd3b352a8f2b21657822d5bd042dd039651e2f082520eaed82dac4e530a3076bce05f2545d001034abcc4@35.201.12.68:30303
enode://91a5fed0112d635f3ded0d350f76b6dadb458157b4d55e491b39c1a7c1d98749867ff2a3b5f4fde2dc839090b1328ca65c6a68f191849d7eb48e5c67dfd2b3cb@35.199.99.105:30303
```
