### ISSUE TITLE
GoChain CLI tool

### ISSUE THREAD

**Issue by treeder** [gochain-io/gochain#328]
While working on a DApp that uses truffle, I feel like the experience could be made a lot nicer/easier. 

For instance, let's say I have a contract I want to deploy, rather than having all of this JavaScript deployment code and needing to run a local blockchain, a simple command like:

```
gochain deploy --network testnet mycontract.sol
```

would compile and deploy the contract.

That's really all that's needed, but maybe have some quick methods to call functions for easy tests after deployment:

```
gochain call --contract 0xABC --function abc()
```

would return a json representation of the call and the details of the call (gas used, etc).

**Comment by jmank88** [comment]
This certainly seems useful. It might be nice to have as a separate repo from gochain itself, so it stays lightweight - would need to import `goclient` and `accounts` at least.

**Comment by treeder** [comment]
Yes, totally agree, this is separate. I used `gochain` as the name since `go` is taken. ;)

**Comment by treeder** [comment]
Could maybe be `gocli` or even `web3`?

**Comment by jmank88** [comment]
Keeping in theme with `chainload`, something like `chainlink`? (could even install as `cl`)

**Comment by landedexperts** [comment]
On Ethereum, there is Remix: https://remix.ethereum.org/#optimize=false
which can also be installed locally through npm, the package is remixd.
Remix is quite complete, although there are some missing options, for example the choice between a "call" and a "send" when calling a method of a smart contract.

I don't know if Remix provides the functionalities OP needs. And Remix is coupled with Ethereum, not GoChain.

Can the endpoint connection of Remix can be changed to a GoChain endpoint, like the open RPC endpoints for GoChain testnet/livenet?

I am certainly interested in the tool OP described :) for interacting easily with contracts on GoChain.

**Comment by jmank88** [comment]
> Can the endpoint connection of Remix can be changed to a GoChain endpoint, like the open RPC endpoints for GoChain testnet/livenet?

Yes, anything Ethereum compatible can be pointed at GoChain RPC endpoints. However, a custom built tool could support our main and test RPC endpoints out of the box, while still allowing for custom RPC endpoints as well (ETH or GO).

**Comment by brockmcblockchain** [comment]
GoRemix would be awesome.  If we could maybe set up a custom config to preload the test and mainnet out of the box.. then still allow custom ones.  (I think remix let's you use metamask config'd networks.)

**Comment by r-kononov** [comment]
@treeder @jmank88 any other useful commands that could be added? (https://github.com/gochain-io/web3-cli/blob/master/main.go)

**Comment by treeder** [comment]
Want to make a WIP PR so we can comment?

Few things:

* can you add Ethereum as a network too?  Probably keeping it open for adding their testnets too. 
* Does deploy do a build then deploy?

**Comment by r-kononov** [comment]
Done - https://github.com/gochain-io/web3-cli/pull/1

 - added Ethereum
- Yep build and deploy (added description for that)

**Comment by treeder** [comment]
Looks like good set of commands to me.

**Comment by treeder** [comment]
Done! https://github.com/gochain-io/web3
