### ISSUE TITLE
Unable to build sources 

### ISSUE THREAD

**Issue by KursLabIgor** [gochain-io/gochain#329]
I have installed go 1.10 and C compiler
when try execute make: 
make dep
dep ensure --vendor-only
make: dep: Command not found
Makefile:12: recipe for target 'dep' failed
make: *** [dep] Error 127

any ideas what can be wrong?

**Comment by KursLabIgor** [comment]
in instruction missed that also should be installed 
https://github.com/golang/dep
After i install any way cant build source 
/root/gochain is not within a known GOPATH/src
Makefile:12: recipe for target 'dep' failed
make: *** [dep] Error 1

**Comment by jmank88** [comment]
It expects to be checked out to `$GOPATH/src/github.com/gochain-io/gochain`. This is a golang restriction.

**Comment by KursLabIgor** [comment]
hmm, ok. let me try first change path.

**Comment by KursLabIgor** [comment]
yes, now works. closed.
