### ISSUE TITLE
Package error 

### ISSUE THREAD

**Issue by kenneth** [gochain-io/gochain#336]
```
➜  gochain git:(master) make all
cd cmd/bootnode; go build -o ../../bin/gochain-bootnode
Done building.
Run "bin/gochain-bootnode" to launch gochain.
cd cmd/gochain; go build -o ../../bin/gochain
main.go:29:2: no Go files in /Users/Documents/GoEnv/src/go.opencensus.io/exporter/stackdriver
make: *** [gochain] Error 1
```

**Comment by jmank88** [comment]
Try running `make dep` first. That should probably be included in `make all`.

**Comment by kenneth** [comment]
i can't get this package

```
go.opencensus.io/exporter/stackdriver
```

**Comment by jmank88** [comment]
It looks like that package does not exist in the latest version on [master](url), but it does exist in [`v0.6.0`](https://github.com/census-instrumentation/opencensus-go/tree/v0.6.0/exporter/stackdriver) which our [`Gopkg.lock`](https://github.com/gochain-io/gochain/blob/master/Gopkg.lock#L25-L29) specifies.

Did you use `make dep`? That should have only vendored what the lock file specified, and not updated any of the dependencies.

**Comment by jmank88** [comment]
This should no longer be an issue after #359.
