### ISSUE TITLE
Problem with new version gochain

### ISSUE THREAD

**Issue by Zzaval** [gochain-io/gochain#343]
I have installed go go1.11.5
and put gochain in $home/src/github.com/gochain-io/gochain/v3/
**PATH=$PATH:/usr/local/go/bin**
GOPATH=$HOME/

when try execute make gochain:
cd cmd/gochain; go build -o ../../bin/gochain
../../trie/database.go:25:2: cannot find package "github.com/allegro/bigcache" in any of:
	/usr/local/go/src/github.com/allegro/bigcache (from $GOROOT)
	/root/src/github.com/allegro/bigcache (from $GOPATH)
../../common/mclock/mclock.go:23:2: cannot find package "github.com/aristanetworks/goarista/monotime" in any of:
	/usr/local/go/src/github.com/aristanetworks/goarista/monotime (from $GOROOT)
	/root/src/github.com/aristanetworks/goarista/monotime (from $GOPATH)
../../ethdb/file_segment.go:16:2: cannot find package "github.com/cespare/xxhash" in any of:
	/usr/local/go/src/github.com/cespare/xxhash (from $GOROOT)
	/root/src/github.com/cespare/xxhash (from $GOPATH)
../../internal/ethapi/api.go:28:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/local/go/src/github.com/davecgh/go-spew/spew (from $GOROOT)
	/root/src/github.com/davecgh/go-spew/spew (from $GOPATH)
../../ethdb/file_segment.go:17:2: cannot find package "github.com/edsrzf/mmap-go" in any of:
	/usr/local/go/src/github.com/edsrzf/mmap-go (from $GOROOT)
	/root/src/github.com/edsrzf/mmap-go (from $GOPATH)
../../dashboard/dashboard.go:37:2: cannot find package "github.com/elastic/gosigar" in any of:
	/usr/local/go/src/github.com/elastic/gosigar (from $GOROOT)
	/root/src/github.com/elastic/gosigar (from $GOPATH)
../../internal/jsre/pretty.go:26:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/root/src/github.com/fatih/color (from $GOPATH)
../../internal/debug/flags.go:27:2: cannot find package "github.com/fjl/memsize/memsizeui" in any of:
	/usr/local/go/src/github.com/fjl/memsize/memsizeui (from $GOROOT)
	/root/src/github.com/fjl/memsize/memsizeui (from $GOPATH)
monitorcmd.go:28:2: cannot find package "github.com/gizak/termui" in any of:
	/usr/local/go/src/github.com/gizak/termui (from $GOROOT)
	/root/src/github.com/gizak/termui (from $GOPATH)
../../log/handler.go:11:2: cannot find package "github.com/go-stack/stack" in any of:
	/usr/local/go/src/github.com/go-stack/stack (from $GOROOT)
	/root/src/github.com/go-stack/stack (from $GOPATH)
../../accounts/usbwallet/internal/trezor/messages.pb.go:6:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/root/src/github.com/golang/protobuf/proto (from $GOPATH)
../../accounts/usbwallet/internal/trezor/types.pb.go:102:8: cannot find package "github.com/golang/protobuf/protoc-gen-go/descriptor" in any of:
	/usr/local/go/src/github.com/golang/protobuf/protoc-gen-go/descriptor (from $GOROOT)
	/root/src/github.com/golang/protobuf/protoc-gen-go/descriptor (from $GOPATH)
../../p2p/rlpx.go:40:2: cannot find package "github.com/golang/snappy" in any of:
	/usr/local/go/src/github.com/golang/snappy (from $GOROOT)
	/root/src/github.com/golang/snappy (from $GOPATH)
../../ethdb/segment_set.go:8:2: cannot find package "github.com/hashicorp/golang-lru" in any of:
	/usr/local/go/src/github.com/hashicorp/golang-lru (from $GOROOT)
	/root/src/github.com/hashicorp/golang-lru (from $GOPATH)
../../p2p/nat/natupnp.go:26:2: cannot find package "github.com/huin/goupnp" in any of:
	/usr/local/go/src/github.com/huin/goupnp (from $GOROOT)
	/root/src/github.com/huin/goupnp (from $GOPATH)
../../p2p/nat/natupnp.go:27:2: cannot find package "github.com/huin/goupnp/dcps/internetgateway1" in any of:
	/usr/local/go/src/github.com/huin/goupnp/dcps/internetgateway1 (from $GOROOT)
	/root/src/github.com/huin/goupnp/dcps/internetgateway1 (from $GOPATH)
../../p2p/nat/natupnp.go:28:2: cannot find package "github.com/huin/goupnp/dcps/internetgateway2" in any of:
	/usr/local/go/src/github.com/huin/goupnp/dcps/internetgateway2 (from $GOROOT)
	/root/src/github.com/huin/goupnp/dcps/internetgateway2 (from $GOPATH)
../../p2p/nat/nat.go:29:2: cannot find package "github.com/jackpal/go-nat-pmp" in any of:
	/usr/local/go/src/github.com/jackpal/go-nat-pmp (from $GOROOT)
	/root/src/github.com/jackpal/go-nat-pmp (from $GOPATH)
../../accounts/usbwallet/hub.go:31:2: cannot find package "github.com/karalabe/hid" in any of:
	/usr/local/go/src/github.com/karalabe/hid (from $GOROOT)
	/root/src/github.com/karalabe/hid (from $GOPATH)
../../internal/debug/flags.go:32:2: cannot find package "github.com/mattn/go-colorable" in any of:
	/usr/local/go/src/github.com/mattn/go-colorable (from $GOROOT)
	/root/src/github.com/mattn/go-colorable (from $GOPATH)
../../ethdb/s3/s3.go:17:2: cannot find package "github.com/minio/minio-go" in any of:
	/usr/local/go/src/github.com/minio/minio-go (from $GOROOT)
	/root/src/github.com/minio/minio-go (from $GOPATH)
config.go:38:2: cannot find package "github.com/naoina/toml" in any of:
	/usr/local/go/src/github.com/naoina/toml (from $GOROOT)
	/root/src/github.com/naoina/toml (from $GOPATH)
../../accounts/keystore/key.go:35:2: cannot find package "github.com/pborman/uuid" in any of:
	/usr/local/go/src/github.com/pborman/uuid (from $GOROOT)
	/root/src/github.com/pborman/uuid (from $GOPATH)
../../console/console.go:35:2: cannot find package "github.com/peterh/liner" in any of:
	/usr/local/go/src/github.com/peterh/liner (from $GOROOT)
	/root/src/github.com/peterh/liner (from $GOPATH)
../../accounts/keystore/watch.go:25:2: cannot find package "github.com/rjeczalik/notify" in any of:
	/usr/local/go/src/github.com/rjeczalik/notify (from $GOROOT)
	/root/src/github.com/rjeczalik/notify (from $GOPATH)
../../internal/jsre/completion.go:23:2: cannot find package "github.com/robertkrimen/otto" in any of:
	/usr/local/go/src/github.com/robertkrimen/otto (from $GOROOT)
	/root/src/github.com/robertkrimen/otto (from $GOPATH)
../../rpc/http.go:34:2: cannot find package "github.com/rs/cors" in any of:
	/usr/local/go/src/github.com/rs/cors (from $GOROOT)
	/root/src/github.com/rs/cors (from $GOPATH)
../../ethdb/db.go:16:2: cannot find package "github.com/syndtr/goleveldb/leveldb" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb (from $GOPATH)
../../p2p/discover/database.go:34:2: cannot find package "github.com/syndtr/goleveldb/leveldb/errors" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/errors (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb/errors (from $GOPATH)
../../ethdb/ldb_segment.go:6:2: cannot find package "github.com/syndtr/goleveldb/leveldb/filter" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/filter (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb/filter (from $GOPATH)
../../ethdb/ldb_segment.go:7:2: cannot find package "github.com/syndtr/goleveldb/leveldb/iterator" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/iterator (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb/iterator (from $GOPATH)
../../ethdb/ldb_segment.go:8:2: cannot find package "github.com/syndtr/goleveldb/leveldb/opt" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOPATH)
../../p2p/discover/database.go:37:2: cannot find package "github.com/syndtr/goleveldb/leveldb/storage" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/storage (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb/storage (from $GOPATH)
../../p2p/discover/database.go:38:2: cannot find package "github.com/syndtr/goleveldb/leveldb/util" in any of:
	/usr/local/go/src/github.com/syndtr/goleveldb/leveldb/util (from $GOROOT)
	/root/src/github.com/syndtr/goleveldb/leveldb/util (from $GOPATH)
main.go:29:2: cannot find package "go.opencensus.io/exporter/stackdriver" in any of:
	/usr/local/go/src/go.opencensus.io/exporter/stackdriver (from $GOROOT)
	/root/src/go.opencensus.io/exporter/stackdriver (from $GOPATH)
../../rpc/http.go:35:2: cannot find package "go.opencensus.io/plugin/ochttp" in any of:
	/usr/local/go/src/go.opencensus.io/plugin/ochttp (from $GOROOT)
	/root/src/go.opencensus.io/plugin/ochttp (from $GOPATH)
../../core/types/derive_sha.go:23:2: cannot find package "go.opencensus.io/trace" in any of:
	/usr/local/go/src/go.opencensus.io/trace (from $GOROOT)
	/root/src/go.opencensus.io/trace (from $GOPATH)
../../accounts/keystore/keystore_passphrase.go:44:2: cannot find package "golang.org/x/crypto/pbkdf2" in any of:
	/usr/local/go/src/golang.org/x/crypto/pbkdf2 (from $GOROOT)
	/root/src/golang.org/x/crypto/pbkdf2 (from $GOPATH)
../../core/vm/contracts.go:29:2: cannot find package "golang.org/x/crypto/ripemd160" in any of:
	/usr/local/go/src/golang.org/x/crypto/ripemd160 (from $GOROOT)
	/root/src/golang.org/x/crypto/ripemd160 (from $GOPATH)
../../accounts/keystore/keystore_passphrase.go:45:2: cannot find package "golang.org/x/crypto/scrypt" in any of:
	/usr/local/go/src/golang.org/x/crypto/scrypt (from $GOROOT)
	/root/src/golang.org/x/crypto/scrypt (from $GOPATH)
../../rpc/websocket.go:34:2: cannot find package "golang.org/x/net/websocket" in any of:
	/usr/local/go/src/golang.org/x/net/websocket (from $GOROOT)
	/root/src/golang.org/x/net/websocket (from $GOPATH)
../../ethdb/segment_set.go:9:2: cannot find package "golang.org/x/sync/semaphore" in any of:
	/usr/local/go/src/golang.org/x/sync/semaphore (from $GOROOT)
	/root/src/golang.org/x/sync/semaphore (from $GOPATH)
../../whisper/whisperv5/whisper.go:36:2: cannot find package "golang.org/x/sync/syncmap" in any of:
	/usr/local/go/src/golang.org/x/sync/syncmap (from $GOROOT)
	/root/src/golang.org/x/sync/syncmap (from $GOPATH)
../../crypto/bn256/cloudflare/gfp_decl.go:9:2: cannot find package "golang.org/x/sys/cpu" in any of:
	/usr/local/go/src/golang.org/x/sys/cpu (from $GOROOT)
	/root/src/golang.org/x/sys/cpu (from $GOPATH)
../../eth/tracers/tracer.go:33:2: cannot find package "gopkg.in/olebedev/go-duktape.v3" in any of:
	/usr/local/go/src/gopkg.in/olebedev/go-duktape.v3 (from $GOROOT)
	/root/src/gopkg.in/olebedev/go-duktape.v3 (from $GOPATH)
../../internal/debug/flags.go:33:2: cannot find package "gopkg.in/urfave/cli.v1" in any of:
	/usr/local/go/src/gopkg.in/urfave/cli.v1 (from $GOROOT)
	/root/src/gopkg.in/urfave/cli.v1 (from $GOPATH)
Makefile:12: recipe for target 'gochain' failed
make: *** [gochain] Error 1

**Comment by jmank88** [comment]
Can you try using `$home/src/github.com/gochain-io/gochain/` (no `v3/`)?

You may also have to fiddle with your `GO111MODULE` env var (blank, auto, or on should work IIRC).

**Comment by Zzaval** [comment]
I change folder and do this  env GO111MODULE=on go build (Error, nothing changed)

go: finding github.com/pborman/uuid v0.0.0-20170612153648-e790cca94e6c
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding github.com/btcsuite/btcd v0.0.0-20180418030112-675abc5df3c5
go: finding github.com/onsi/gomega v1.4.3
go: finding github.com/fjl/memsize v0.0.0-20180929194037-2a09253e352a
go: finding github.com/maruel/panicparse v1.1.1
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/nsf/termbox-go v0.0.0-20180502020344-5a49b8216054
go: finding github.com/gopherjs/gopherjs v0.0.0-20181103185306-d547d1d9531e
go: finding gopkg.in/ini.v1 v1.41.0
go: finding github.com/docker/docker v1.13.1
go: finding github.com/peterh/liner v0.0.0-20180310181206-6106ee4fe3e8
go: finding github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: finding github.com/golang/protobuf v1.2.0
go: finding go.opencensus.io v0.14.0
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding github.com/cespare/xxhash v1.0.0
go: finding google.golang.org/api v0.0.0-20180904000447-0ad5a633fea1
go: finding gopkg.in/olebedev/go-duktape.v3 v3.0.0-20180302121509-abf0ba0be5d5
go: finding github.com/smartystreets/goconvey v0.0.0-20181108003508-044398e4856c
go: finding gopkg.in/sourcemap.v1 v1.0.5
go: finding github.com/golang/snappy v0.0.0-20170215233205-553a64147049
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding github.com/minio/minio-go v6.0.13+incompatible
go: finding cloud.google.com/go v0.27.0
go: finding github.com/naoina/go-stringutil v0.1.0
go: finding github.com/go-ini/ini v1.36.0
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/aristanetworks/goarista v0.0.0-20180424004133-70dca2f27708
go: finding github.com/OneOfOne/xxhash v1.2.2
go: finding google.golang.org/appengine v1.1.0
go: finding github.com/julienschmidt/httprouter v1.1.0
go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding gopkg.in/natefinch/npipe.v2 v2.0.0-20160621034901-c1b8fa8bdcce
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding golang.org/x/text v0.3.0
go: finding github.com/StackExchange/wmi v0.0.0-20180116203802-5d049714c4a6
go: finding github.com/kylelemons/godebug v0.0.0-20170820004349-d65d576e9348
go: finding github.com/huin/goupnp v0.0.0-20180415215157-1395d1447324
go: finding github.com/onsi/ginkgo v1.7.0
go: finding github.com/jackpal/go-nat-pmp v1.0.1
go: finding gopkg.in/urfave/cli.v1 v1.20.0
go: finding golang.org/x/crypto v0.0.0-20180503153109-76a954637dfa
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding github.com/naoina/toml v0.1.1
go: finding contrib.go.opencensus.io/exporter/stackdriver v0.6.0
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding github.com/mitchellh/go-homedir v0.0.0-20161203194507-b8bc1bf76747
go: finding github.com/smartystreets/assertions v0.0.0-20190116191733-b6c0e53d7304
go: finding google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
go: finding github.com/go-ole/go-ole v1.2.1
go: finding github.com/influxdata/influxdb v1.6.3
go: finding github.com/rjeczalik/notify v0.9.1
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/syndtr/goleveldb v0.0.0-20180502072349-ae970a0732be
go: finding github.com/spaolacci/murmur3 v0.0.0-20180118202830-f09979ecbc72
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding github.com/go-stack/stack v1.7.0
go: finding github.com/mitchellh/go-wordwrap v0.0.0-20150314170334-ad45545899c7
go: finding github.com/olekukonko/tablewriter v0.0.0-20180418011723-d5dd8a50526a
go: finding github.com/fatih/color v1.6.0
go: finding github.com/stretchr/testify v1.2.1
go: finding bazil.org/fuse v0.0.0-20180421153158-65cc252bf669
go: finding github.com/elastic/gosigar v0.0.0-20180330100440-37f05ff46ffa
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding google.golang.org/grpc v1.14.0
go: finding github.com/mattn/go-runewidth v0.0.2
go: finding golang.org/x/tools v0.0.0-20190121143147-24cd39ecf745
go: finding github.com/gizak/termui v2.2.0+incompatible
go: finding github.com/cespare/cp v1.0.0
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/allegro/bigcache v1.1.0
go: finding github.com/jtolds/gls v4.2.1+incompatible
go: finding github.com/rs/cors v1.3.0
go: finding github.com/mattn/go-colorable v0.0.9
go: finding github.com/onsi/ginkgo v1.6.0
go: finding github.com/robertkrimen/otto v0.0.0-20180305042045-6c383dd335ef
go: finding github.com/hpcloud/tail v1.0.0
go: finding github.com/karalabe/hid v0.0.0-20180420081245-2b4488a37358
go: finding github.com/googleapis/gax-go v2.0.0+incompatible
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
go: finding gopkg.in/check.v1 v1.0.0-20161208181325-20d25e280405
go: finding github.com/mattn/go-isatty v0.0.3
go: downloading github.com/syndtr/goleveldb v0.0.0-20180502072349-ae970a0732be
go: downloading go.opencensus.io v0.14.0
go: downloading github.com/allegro/bigcache v1.1.0
go: downloading github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: downloading github.com/cespare/xxhash v1.0.0
go: downloading golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: downloading github.com/go-stack/stack v1.7.0
go: downloading github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
go: downloading golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: downloading github.com/golang/snappy v0.0.0-20170215233205-553a64147049
