### ISSUE TITLE
Log in deamon

### ISSUE THREAD

**Issue by Zzaval** [gochain-io/gochain#345]
gochain --testnet --datadir /root/GoChain/node --cache 512 --rpc --ws --wsorigins "*" --rpcapi eth,net,web3,debug --wsapi eth,net,web3,debug --syncmode full --gcmode "full" 2>> /var/log/gochain.log

When I send this string in terminal, all working, log writing in file.

But this string in my daemon don`t write log in file, can you help me please. 

[Service]
Type=simple
ExecStart=/root/src/github.com/gochain-io/gochain/bin/gochain --testnet --datadir /root/GoChain/node --cache 512 --rpc --ws --wsorigins "*" --rpcapi eth,net,web3,debug --wsapi eth,net,web3,debug --syncmode full --gcmode "full" 2>> /var/log/gochain.log
[Install]
WantedBy=default.target

**Comment by treeder** [comment]
Are you trying to have nothing write to the terminal?  only to the logs?

**Comment by Zzaval** [comment]
I want to write all the logs in a separate file.
There may be a way to resolve this. Can you help me?

**Comment by jmank88** [comment]
What daemon service are you using? This seems like a daemon configuration problem, unrelated to GoChain.
