### ISSUE TITLE
One line docker command to startup test chain

### ISSUE THREAD

**Issue by treeder** [gochain-io/gochain#347]
eg: 

```sh
docker run --rm -it -v $PWD:/gochain -w /gochain gochain/gochain --dev
```

If first time starting (ie: no data exists) it would return the coinbase private key so the user can then immediately start interacting with it.

**Comment by jmank88** [comment]
I think you can drop at least the `-v` and `-w` options.

Must it be a one liner? It is difficult to log information for the user that doesn't immediately scroll away in a flood of logs. It is also not necessary for the node to know the private key or unlock the account.

Instead, we could just add a flag for a seed account to fund, e.g. `--dev.seed 0x1234`. And the user would use an existing account, or create a new one via e.g. `gochain account new` or `web3 account new`.

**Comment by treeder** [comment]
Seeding another account could work too. 

I think we need the -v and -w though so the data sticks, we don't want it to wipe every time you stop the container.

**Comment by jmank88** [comment]
`--dev` mode is specifically designed to be ephemeral and use only an in-memory database. We'd have to make some changes to allow persistence, but then the one-liner would include options used only during the first execution, and ignored later. It may make more sense to streamline setting up with a randomized genesis file as a first step, then running plain gochain after that. The init step could create the signing account, write a partially randomized genesis file to the data dir, and optionally accept a seed account if they want to use an existing one. Then they just run plain `gochain` after that.

Seed an existing account:
```sh
> gochain init-random --seed=0x1234
Wrote genesis to <datadir>
Seeded account 0x1234 with 1,000,000,000 GO
> gochain
```

Seed a random account, dump the details:
```sh
> gochain init-random --private-key
Created Account: 0x1234
Private Key: 0x5678
Wrote genesis to <datadir>
Seeded account 0x1234 with 1,000,000,000 GO
> gochain
```

**Comment by jmank88** [comment]
One option to simplify things a bit would be to provide a docker-compose file with the messy volume and port options set, and then have them run the first command via `docker-compose run`, so that they don't have to include all that stuff on the command line themselves. We can also set defaults and let them override with an `.env` file with this approach.
