### ISSUE TITLE
Problem with Gochain Testnet.

### ISSUE THREAD

**Issue by Zzaval** [gochain-io/gochain#351]
Help me please.

e.g  gochain --testnet --datadir /mnt/gchtest_volume/GochainDB/node --cache 512 --rpc --ws --wsorigins "*" --rpcapi eth,net,web3,debug --wsapi eth,net,web3,debug --syncmode full --gcmode "full"

Gochain last synced block 0xa924 and then sent error:

("jsonrpc":"2.0","id":1,"result":{"currentBlock":"0xa924","highestBlock":"0x306fa8","knownStates":"0x0","pulledStates":"0x0","startingBlock":"0x661a"}})

0|gochain  | INFO [02-05|10:17:56] Failed to send rlpx disc msg while closing err="write tcp myip:58848->165.227.163.103:30303: write: broken pipe"
0|gochain  | INFO [02-05|10:18:05] Failed to send rlpx disc msg while closing err="write tcp myip:30303->120.77.102.101:59020: write: connection reset by peer"

**Comment by jmank88** [comment]
Those are actually a common part of peer management, which is why they logged `INFO` rather than `WARN` or `ERROR`. The node should continue operating just fine.
