### ISSUE TITLE
Unable to build sources

### ISSUE THREAD

**Issue by wbdeedcoin** [gochain-io/gochain#353]
warren@dev:~/go/src/github.com/gochain$ make gochain
cd cmd/gochain; go build -o ../../bin/gochain
<details><summary>Output</summary>
<p>
main.go:29:2: cannot find package "contrib.go.opencensus.io/exporter/stackdriver" in any of:
/usr/src/contrib.go.opencensus.io/exporter/stackdriver (from $GOROOT)
/home/warren/go/src/contrib.go.opencensus.io/exporter/stackdriver (from $GOPATH)
monitorcmd.go:28:2: cannot find package "github.com/gizak/termui" in any of:
/usr/src/github.com/gizak/termui (from $GOROOT)
/home/warren/go/src/github.com/gizak/termui (from $GOPATH)
accountcmd.go:23:2: cannot find package "github.com/gochain-io/gochain/v3/accounts" in any of:
/usr/src/github.com/gochain-io/gochain/v3/accounts (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/accounts (from $GOPATH)
accountcmd.go:24:2: cannot find package "github.com/gochain-io/gochain/v3/accounts/keystore" in any of:
/usr/src/github.com/gochain-io/gochain/v3/accounts/keystore (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/accounts/keystore (from $GOPATH)
bugcmd.go:29:2: cannot find package "github.com/gochain-io/gochain/v3/cmd/internal/browser" in any of:
/usr/src/github.com/gochain-io/gochain/v3/cmd/internal/browser (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/cmd/internal/browser (from $GOPATH)
accountcmd.go:25:2: cannot find package "github.com/gochain-io/gochain/v3/cmd/utils" in any of:
/usr/src/github.com/gochain-io/gochain/v3/cmd/utils (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/cmd/utils (from $GOPATH)
chaincmd.go:30:2: cannot find package "github.com/gochain-io/gochain/v3/common" in any of:
/usr/src/github.com/gochain-io/gochain/v3/common (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/common (from $GOPATH)
accountcmd.go:26:2: cannot find package "github.com/gochain-io/gochain/v3/console" in any of:
/usr/src/github.com/gochain-io/gochain/v3/console (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/console (from $GOPATH)
chaincmd.go:32:2: cannot find package "github.com/gochain-io/gochain/v3/core" in any of:
/usr/src/github.com/gochain-io/gochain/v3/core (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/core (from $GOPATH)
chaincmd.go:33:2: cannot find package "github.com/gochain-io/gochain/v3/core/state" in any of:
/usr/src/github.com/gochain-io/gochain/v3/core/state (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/core/state (from $GOPATH)
chaincmd.go:34:2: cannot find package "github.com/gochain-io/gochain/v3/core/types" in any of:
/usr/src/github.com/gochain-io/gochain/v3/core/types (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/core/types (from $GOPATH)
accountcmd.go:27:2: cannot find package "github.com/gochain-io/gochain/v3/crypto" in any of:
/usr/src/github.com/gochain-io/gochain/v3/crypto (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/crypto (from $GOPATH)
config.go:32:2: cannot find package "github.com/gochain-io/gochain/v3/dashboard" in any of:
/usr/src/github.com/gochain-io/gochain/v3/dashboard (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/dashboard (from $GOPATH)
config.go:33:2: cannot find package "github.com/gochain-io/gochain/v3/eth" in any of:
/usr/src/github.com/gochain-io/gochain/v3/eth (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/eth (from $GOPATH)
chaincmd.go:35:2: cannot find package "github.com/gochain-io/gochain/v3/eth/downloader" in any of:
/usr/src/github.com/gochain-io/gochain/v3/eth/downloader (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/eth/downloader (from $GOPATH)
chaincmd.go:36:2: cannot find package "github.com/gochain-io/gochain/v3/ethdb" in any of:
/usr/src/github.com/gochain-io/gochain/v3/ethdb (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/ethdb (from $GOPATH)
chaincmd.go:37:2: cannot find package "github.com/gochain-io/gochain/v3/event" in any of:
/usr/src/github.com/gochain-io/gochain/v3/event (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/event (from $GOPATH)
main.go:39:2: cannot find package "github.com/gochain-io/gochain/v3/goclient" in any of:
/usr/src/github.com/gochain-io/gochain/v3/goclient (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/goclient (from $GOPATH)
main.go:40:2: cannot find package "github.com/gochain-io/gochain/v3/internal/debug" in any of:
/usr/src/github.com/gochain-io/gochain/v3/internal/debug (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/internal/debug (from $GOPATH)
accountcmd.go:28:2: cannot find package "github.com/gochain-io/gochain/v3/log" in any of:
/usr/src/github.com/gochain-io/gochain/v3/log (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/log (from $GOPATH)
main.go:42:2: cannot find package "github.com/gochain-io/gochain/v3/metrics" in any of:
/usr/src/github.com/gochain-io/gochain/v3/metrics (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/metrics (from $GOPATH)
config.go:34:2: cannot find package "github.com/gochain-io/gochain/v3/netstats" in any of:
/usr/src/github.com/gochain-io/gochain/v3/netstats (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/netstats (from $GOPATH)
config.go:35:2: cannot find package "github.com/gochain-io/gochain/v3/node" in any of:
/usr/src/github.com/gochain-io/gochain/v3/node (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/node (from $GOPATH)
bugcmd.go:30:2: cannot find package "github.com/gochain-io/gochain/v3/params" in any of:
/usr/src/github.com/gochain-io/gochain/v3/params (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/params (from $GOPATH)
consolecmd.go:30:2: cannot find package "github.com/gochain-io/gochain/v3/rpc" in any of:
/usr/src/github.com/gochain-io/gochain/v3/rpc (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/rpc (from $GOPATH)
config.go:37:2: cannot find package "github.com/gochain-io/gochain/v3/whisper/whisperv5" in any of:
/usr/src/github.com/gochain-io/gochain/v3/whisper/whisperv5 (from $GOROOT)
/home/warren/go/src/github.com/gochain-io/gochain/v3/whisper/whisperv5 (from $GOPATH)
config.go:38:2: cannot find package "github.com/naoina/toml" in any of:
/usr/src/github.com/naoina/toml (from $GOROOT)
/home/warren/go/src/github.com/naoina/toml (from $GOPATH)
main.go:30:2: cannot find package "go.opencensus.io/trace" in any of:
/usr/src/go.opencensus.io/trace (from $GOROOT)
/home/warren/go/src/go.opencensus.io/trace (from $GOPATH)
accountcmd.go:29:2: cannot find package "gopkg.in/urfave/cli.v1" in any of:
/usr/src/gopkg.in/urfave/cli.v1 (from $GOROOT)
/home/warren/go/src/gopkg.in/urfave/cli.v1 (from $GOPATH)
Makefile:12: recipe for target 'gochain' failed
make: *** [gochain] Error 1
</p>
</details>

**Comment by jmank88** [comment]
Which version of the code do you have checked out?
Which version of `go` are you running?
Do you have go modules enabled?

**Comment by wbdeedcoin** [comment]
> Which version of the code do you have checked out?

the current one on master

> Which version of `go` are you running?

1.11

> Do you have go modules enabled?

as far as I can tell.

**Comment by jmank88** [comment]
Do you have the environment variable `GO111MODULE` set to `on`?

**Comment by jmank88** [comment]
That's std lib, so it seems like a modules problem. Can you try `go1.12beta2`? You can test without replacing your existing install by running `go get golang.org/dl/go1.12beta2`

**Comment by wbdeedcoin** [comment]
@jmank88 

warren@dev:~/go/src/github.com/gochain$ go get golang.org/dl/go1.12beta2
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'

**Comment by treeder** [comment]
@wbdeedcoin now you should be able to use `go1.12beta2`, try:

```sh
cd cmd/gochain
go1.12beta2 build -o ../../bin/gochain
```

**Comment by wbdeedcoin** [comment]
warren@dev:~/.../gochain/cmd/gochain$ go get golang.org/dl/go1.12beta2
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring ../../go.mod;
	see 'go help modules'

**Comment by treeder** [comment]
I just see a warning, did you try what I said?

Also, try doing the go get `go get golang.org/dl/go1.12beta2` in a non working directory so it doesn't try to add it to the GoChain go.mod.

**Comment by wbdeedcoin** [comment]
warren@dev:~/.../gochain/cmd/gochain$ go1.12beta2 build -o ../../bin/gochain
go1.12beta2: command not found

**Comment by wbdeedcoin** [comment]
warren@dev:~/.../github.com/gochain-io/gochain$ make gochain
cd cmd/gochain; go build -o ../../bin/gochain
main.go:29:2: cannot find package "contrib.go.opencensus.io/exporter/stackdriver" in any of:
	/usr/local/go/src/contrib.go.opencensus.io/exporter/stackdriver (from $GOROOT)
	/home/warren/go/src/contrib.go.opencensus.io/exporter/stackdriver (from $GOPATH)
../../common/mclock/mclock.go:23:2: cannot find package "github.com/aristanetworks/goarista/monotime" in any of:
	/usr/local/go/src/github.com/aristanetworks/goarista/monotime (from $GOROOT)
	/home/warren/go/src/github.com/aristanetworks/goarista/monotime (from $GOPATH)
../../internal/ethapi/api.go:28:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/local/go/src/github.com/davecgh/go-spew/spew (from $GOROOT)
	/home/warren/go/src/github.com/davecgh/go-spew/spew (from $GOPATH)
../../dashboard/dashboard.go:37:2: cannot find package "github.com/elastic/gosigar" in any of:
	/usr/local/go/src/github.com/elastic/gosigar (from $GOROOT)
	/home/warren/go/src/github.com/elastic/gosigar (from $GOPATH)
../../internal/jsre/pretty.go:26:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/home/warren/go/src/github.com/fatih/color (from $GOPATH)
../../internal/debug/flags.go:27:2: cannot find package "github.com/fjl/memsize/memsizeui" in any of:
	/usr/local/go/src/github.com/fjl/memsize/memsizeui (from $GOROOT)
	/home/warren/go/src/github.com/fjl/memsize/memsizeui (from $GOPATH)
monitorcmd.go:28:2: cannot find package "github.com/gizak/termui" in any of:
	/usr/local/go/src/github.com/gizak/termui (from $GOROOT)
	/home/warren/go/src/github.com/gizak/termui (from $GOPATH)
../../accounts/usbwallet/internal/trezor/messages.pb.go:6:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/home/warren/go/src/github.com/golang/protobuf/proto (from $GOPATH)
../../accounts/usbwallet/internal/trezor/types.pb.go:102:8: cannot find package "github.com/golang/protobuf/protoc-gen-go/descriptor" in any of:
	/usr/local/go/src/github.com/golang/protobuf/protoc-gen-go/descriptor (from $GOROOT)
	/home/warren/go/src/github.com/golang/protobuf/protoc-gen-go/descriptor (from $GOPATH)
../../p2p/nat/natupnp.go:26:2: cannot find package "github.com/huin/goupnp" in any of:
	/usr/local/go/src/github.com/huin/goupnp (from $GOROOT)
	/home/warren/go/src/github.com/huin/goupnp (from $GOPATH)
../../p2p/nat/natupnp.go:27:2: cannot find package "github.com/huin/goupnp/dcps/internetgateway1" in any of:
	/usr/local/go/src/github.com/huin/goupnp/dcps/internetgateway1 (from $GOROOT)
	/home/warren/go/src/github.com/huin/goupnp/dcps/internetgateway1 (from $GOPATH)
../../p2p/nat/natupnp.go:28:2: cannot find package "github.com/huin/goupnp/dcps/internetgateway2" in any of:
	/usr/local/go/src/github.com/huin/goupnp/dcps/internetgateway2 (from $GOROOT)
	/home/warren/go/src/github.com/huin/goupnp/dcps/internetgateway2 (from $GOPATH)
../../p2p/nat/nat.go:29:2: cannot find package "github.com/jackpal/go-nat-pmp" in any of:
	/usr/local/go/src/github.com/jackpal/go-nat-pmp (from $GOROOT)
	/home/warren/go/src/github.com/jackpal/go-nat-pmp (from $GOPATH)
../../accounts/usbwallet/hub.go:31:2: cannot find package "github.com/karalabe/hid" in any of:
	/usr/local/go/src/github.com/karalabe/hid (from $GOROOT)
	/home/warren/go/src/github.com/karalabe/hid (from $GOPATH)
../../internal/debug/flags.go:32:2: cannot find package "github.com/mattn/go-colorable" in any of:
	/usr/local/go/src/github.com/mattn/go-colorable (from $GOROOT)
	/home/warren/go/src/github.com/mattn/go-colorable (from $GOPATH)
../../ethdb/s3/s3.go:17:2: cannot find package "github.com/minio/minio-go" in any of:
	/usr/local/go/src/github.com/minio/minio-go (from $GOROOT)
	/home/warren/go/src/github.com/minio/minio-go (from $GOPATH)
config.go:38:2: cannot find package "github.com/naoina/toml" in any of:
	/usr/local/go/src/github.com/naoina/toml (from $GOROOT)
	/home/warren/go/src/github.com/naoina/toml (from $GOPATH)
../../accounts/keystore/key.go:35:2: cannot find package "github.com/pborman/uuid" in any of:
	/usr/local/go/src/github.com/pborman/uuid (from $GOROOT)
	/home/warren/go/src/github.com/pborman/uuid (from $GOPATH)
../../console/console.go:35:2: cannot find package "github.com/peterh/liner" in any of:
	/usr/local/go/src/github.com/peterh/liner (from $GOROOT)
	/home/warren/go/src/github.com/peterh/liner (from $GOPATH)
../../accounts/keystore/watch.go:25:2: cannot find package "github.com/rjeczalik/notify" in any of:
	/usr/local/go/src/github.com/rjeczalik/notify (from $GOROOT)
	/home/warren/go/src/github.com/rjeczalik/notify (from $GOPATH)
../../internal/jsre/completion.go:23:2: cannot find package "github.com/robertkrimen/otto" in any of:
	/usr/local/go/src/github.com/robertkrimen/otto (from $GOROOT)
	/home/warren/go/src/github.com/robertkrimen/otto (from $GOPATH)
../../rpc/http.go:34:2: cannot find package "github.com/rs/cors" in any of:
	/usr/local/go/src/github.com/rs/cors (from $GOROOT)
	/home/warren/go/src/github.com/rs/cors (from $GOPATH)
../../rpc/websocket.go:34:2: cannot find package "golang.org/x/net/websocket" in any of:
	/usr/local/go/src/golang.org/x/net/websocket (from $GOROOT)
	/home/warren/go/src/golang.org/x/net/websocket (from $GOPATH)
../../eth/tracers/tracer.go:33:2: cannot find package "gopkg.in/olebedev/go-duktape.v3" in any of:
	/usr/local/go/src/gopkg.in/olebedev/go-duktape.v3 (from $GOROOT)
	/home/warren/go/src/gopkg.in/olebedev/go-duktape.v3 (from $GOPATH)
../../internal/debug/flags.go:33:2: cannot find package "gopkg.in/urfave/cli.v1" in any of:
	/usr/local/go/src/gopkg.in/urfave/cli.v1 (from $GOROOT)
	/home/warren/go/src/gopkg.in/urfave/cli.v1 (from $GOPATH)
Makefile:12: recipe for target 'gochain' failed
make: *** [gochain] Error 1

**Comment by wbdeedcoin** [comment]
Okay if my GOPATH is $HOME/go what should my GOROOT be?

**Comment by treeder** [comment]
You shouldn't need to set GOROOT.

If you're up for it, just install go1.12 fully, it should solve any of these issues: https://golang.org/dl/#unstable

Also, you won't need to put your code in GOPATH anymore either (probably best not to). You can read more about go modules here: https://github.com/golang/go/wiki/Modules

**Comment by wbdeedcoin** [comment]
@treeder I uninstalled g01.11 and installed go1.12 still same errors.

**Comment by treeder** [comment]
Did you ever get this sorted?  Gotta be something configured incorrectly on your side as it works for all of us. I would try unsetting GOPATH and GOROOT, uninstalling your current installation then reinstalling.

**Comment by wbdeedcoin** [comment]
> Did you ever get this sorted? Gotta be something configured incorrectly on your side as it works for all of us. I would try unsetting GOPATH and GOROOT, uninstalling your current installation then reinstalling.

Yes the problem was trying to build the project inside of the same dir as GOPATH and GOROOT. I installed in another dir and it built just fine. I'll close this.
