### ISSUE TITLE
Problem with Gochain TestNet after resized volume.

### ISSUE THREAD

**Issue by Zzaval** [gochain-io/gochain#373]
I took 2500000 blocks and undestend that my volume is not much and I resized volume to bigger. In digitalOcean I did it, and on server write command "sudo resize2fs /dev/sda" .
After that I have error : 

INFO [03-18|12:46:15] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-18|12:46:15] Starting peer-to-peer node               instance=GoChain/v3.1.5/linux-amd64/go1.12beta1
INFO [03-18|12:46:32] Persisted trie from memory database      nodes=1 size=152.00B time=17.338µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-18|12:46:32] Initialised chain configuration          config="{ChainID: 31337 Homestead: 0 EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 4081350 ConstantinopleFix: <nil> EWASM: <nil> Engine: clique}"
INFO [03-18|12:46:32] Initialising GoChain protocol            versions="[63 62]" network=31337
ERROR[03-18|12:46:32] Failed to decode database version        encoded=[]
ERROR[03-18|12:46:32] Failed to encode database version        version=3
INFO [03-18|12:46:32] Loaded most recent local header          number=2504599 hash=736697…c293ff td=12993717
INFO [03-18|12:46:32] Loaded most recent local full block      number=2504599 hash=736697…c293ff td=12993717
INFO [03-18|12:46:32] Loaded most recent local fast block      number=2504599 hash=736697…c293ff td=12993717
INFO [03-18|12:46:32] Resetting tx pool                        old=nil newnum=2504599 newhash=736697…c293ff
INFO [03-18|12:46:32] Reset tx pool                            dur=129.204µs
INFO [03-18|12:46:32] Loaded local transaction journal         transactions=0 dropped=0
INFO [03-18|12:46:32] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-18|12:46:32] Starting P2P networking 
INFO [03-18|12:46:35] UDP listener up                          self=enode://**********@[::]:30303
INFO [03-18|12:46:35] RLPx listener up                         self=enode://**********@[::]:30303
INFO [03-18|12:46:35] IPC endpoint opened                      url=/mnt/my_volume/GochainDB_OLD/node/gochain.ipc
WARN [03-18|12:46:35] Sanitizing invalid HTTP read timeout     provided=0s updated=30s
WARN [03-18|12:46:35] Sanitizing invalid HTTP write timeout    provided=0s updated=30s
WARN [03-18|12:46:35] Sanitizing invalid HTTP idle timeout     provided=0s updated=2m0s
INFO [03-18|12:46:35] HTTP endpoint opened                     url=http://127.0.0.1:8545                                       cors= vhosts=localhost
INFO [03-18|12:46:35] WebSocket endpoint opened                url=ws://127.0.0.1:8546
INFO [03-18|12:47:24] Failed to send rlpx disc msg while closing err="write tcp myip:55286->myip:30305: write: broken pipe"

**Comment by jmank88** [comment]
What is the error? The database version ERROR lines are nbd. That is a long time bug inherited from geth, but doesn't actually break anything. Everything else looks normal as WARN or INFO.

**Comment by Zzaval** [comment]
I waiting 30 min. and see only this messages. It`s normal? 


0|script  | WARN [03-18|14:36:18] Sanitizing invalid HTTP read timeout     provided=0s updated=30s
0|script  | WARN [03-18|14:36:18] Sanitizing invalid HTTP write timeout    provided=0s updated=30s
0|script  | WARN [03-18|14:36:18] Sanitizing invalid HTTP idle timeout     provided=0s updated=2m0s
0|script  | INFO [03-18|14:36:18] HTTP endpoint opened                     url=http://127.0.0.1:8545                                   cors= vhosts=localhost
0|script  | INFO [03-18|14:36:18] WebSocket endpoint opened                url=ws://127.0.0.1:8546
0|script  | INFO [03-18|14:36:26] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:34358->178.128.192.208:30300: write: connection reset by peer"
0|script  | INFO [03-18|14:39:53] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:35240->178.128.192.208:30300: write: connection reset by peer"
0|script  | INFO [03-18|14:40:56] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:35512->178.128.192.208:30300: write: connection reset by peer"
0|script  | INFO [03-18|14:45:12] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:55018->82.135.139.249:30303: write: connection reset by peer"
0|script  | INFO [03-18|14:45:47] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:51132->207.154.228.74:30305: write: broken pipe"
0|script  | INFO [03-18|14:46:56] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:36878->178.128.192.208:30300: write: connection reset by peer"
0|script  | ERROR[03-18|14:47:09] Cannot decode disc msg payload           id=85df2e6b34848ac2 conn=dyndial msg= err="rlp: expected input list for [1]p2p.DiscReason"
0|script  | ERROR[03-18|14:48:34] Cannot decode disc msg payload           id=85df2e6b34848ac2 conn=dyndial msg= err="rlp: expected input list for [1]p2p.DiscReason"
0|script  | INFO [03-18|14:50:12] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:37732->178.128.192.208:30300: write: connection reset by peer"
0|script  | INFO [03-18|14:51:56] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:47228->91.107.64.143:30303: write: connection reset by peer"
0|script  | INFO [03-18|14:52:52] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:52926->207.154.228.74:30305: write: broken pipe"
0|script  | INFO [03-18|14:57:17] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:39458->178.128.192.208:30300: write: connection reset by peer"
0|script  | INFO [03-18|14:57:57] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:51798->159.89.99.131:30303: write: broken pipe"
0|script  | INFO [03-18|15:05:04] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:41344->178.128.192.208:30300: write: connection reset by peer"
0|script  | INFO [03-18|15:07:52] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:56560->207.154.228.74:30305: write: broken pipe"
0|script  | INFO [03-18|15:08:17] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:48096->192.99.244.28:30303: write: connection reset by peer"
0|script  | INFO [03-18|15:10:25] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:57166->207.154.228.74:30305: write: broken pipe"
0|script  | INFO [03-18|15:11:21] Failed to send rlpx disc msg while closing err="write tcp 207.154.237.42:57394->207.154.228.74:30305: write: connection reset by peer"

**Comment by jmank88** [comment]
Those logs look normal, but it should find peers faster, especially if it was running before. Do any peers come up in the console? `admin.peers`

**Comment by Zzaval** [comment]
Thank you!!! I waiting 1 h, and all right!
